# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainPageUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("NN2GUI")
        MainWindow.resize(946, 703)
        MainWindow.setStyleSheet("background-color: rgb(22, 26, 29);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.pushButton    = QtWidgets.QPushButton(self.centralwidget)
        self.label         = QtWidgets.QLabel(self.centralwidget)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setGeometry(QtCore.QRect(370, 450, 200, 40))
        self.label.setGeometry(QtCore.QRect(240, 120, 471, 201))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 20px;\n"
"    background-color: #BA181B;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}")
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Upload Model"))
        self.label.setText(_translate("MainWindow", "Waiting passionately for a model!"))
