# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NN2GUI(object):
    def setupUi(self, NN2GUI):
        NN2GUI.setObjectName("NN2GUI")
        NN2GUI.resize(1000, 750)
        NN2GUI.setMinimumSize(QtCore.QSize(1000, 750))
        NN2GUI.setMaximumSize(QtCore.QSize(1000, 750))
        font = QtGui.QFont()
        font.setPointSize(9)
        NN2GUI.setFont(font)
        NN2GUI.setStyleSheet("background-color: rgb(22, 26, 29);")
        self.centralwidget = QtWidgets.QWidget(NN2GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.model_spec = QtWidgets.QLabel(self.centralwidget)
        self.model_spec.setEnabled(True)
        self.model_spec.setGeometry(QtCore.QRect(480, 190, 492, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.model_spec.sizePolicy().hasHeightForWidth())
        self.model_spec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.model_spec.setFont(font)
        self.model_spec.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.model_spec.setTextFormat(QtCore.Qt.PlainText)
        self.model_spec.setScaledContents(False)
        self.model_spec.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.model_spec.setWordWrap(True)
        self.model_spec.setObjectName("model_spec")
        self.enter_input = QtWidgets.QPushButton(self.centralwidget)
        self.enter_input.setGeometry(QtCore.QRect(170, 572, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.enter_input.sizePolicy().hasHeightForWidth())
        self.enter_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.enter_input.setFont(font)
        self.enter_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enter_input.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BA181B;\n"
"}")
        self.enter_input.setObjectName("enter_input")
        self.framework_type = QtWidgets.QComboBox(self.centralwidget)
        self.framework_type.setGeometry(QtCore.QRect(70, 200, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.framework_type.sizePolicy().hasHeightForWidth())
        self.framework_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.framework_type.setFont(font)
        self.framework_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.framework_type.setStyleSheet("QComboBox{\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"    padding: 2px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #E5383B;\n"
"    selection-background-color: #A4161A;\n"
"    color: #F5F3F4;\n"
"    background-color: #0B090A;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"    background-color: #BA181B;\n"
"}")
        self.framework_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.framework_type.setObjectName("framework_type")
        self.framework_type.addItem("")
        self.framework_type.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 120, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 290, 120, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.output_classes = QtWidgets.QPushButton(self.centralwidget)
        self.output_classes.setGeometry(QtCore.QRect(260, 200, 91, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.output_classes.sizePolicy().hasHeightForWidth())
        self.output_classes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.output_classes.setFont(font)
        self.output_classes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.output_classes.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}")
        self.output_classes.setObjectName("output_classes")
        self.input_input = QtWidgets.QTextEdit(self.centralwidget)
        self.input_input.setGeometry(QtCore.QRect(35, 375, 380, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_input.sizePolicy().hasHeightForWidth())
        self.input_input.setSizePolicy(sizePolicy)
        self.input_input.setMinimumSize(QtCore.QSize(0, 192))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        self.input_input.setFont(font)
        self.input_input.setStyleSheet("QTextEdit {\n"
"    border-radius: 15px;\n"
"    border: 1px solid #E5383B;\n"
"    padding: 5px;\n"
"    color: #F5F3F4;\n"
"}\n"
"\n"
"QTextEdit:disabled {\n"
"    background-color: #BA181B;\n"
"}")
        self.input_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_input.setAcceptRichText(True)
        self.input_input.setObjectName("input_input")
        self.input_type = QtWidgets.QComboBox(self.centralwidget)
        self.input_type.setGeometry(QtCore.QRect(70, 90, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.input_type.sizePolicy().hasHeightForWidth())
        self.input_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.input_type.setFont(font)
        self.input_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.input_type.setStyleSheet("QComboBox{\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"    padding: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    image: url(:/gallery/arrow-down.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #E5383B;\n"
"    selection-background-color: #A4161A;\n"
"    color: #F5F3F4;\n"
"    background-color: #0B090A;\n"
"    border-radius: 5px;\n"
"}")
        self.input_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.input_type.setObjectName("input_type")
        self.input_type.addItem("")
        self.input_type.addItem("")
        self.input_type.addItem("")
        self.input_type.addItem("")
        self.output_type = QtWidgets.QComboBox(self.centralwidget)
        self.output_type.setGeometry(QtCore.QRect(270, 90, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.output_type.sizePolicy().hasHeightForWidth())
        self.output_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.output_type.setFont(font)
        self.output_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.output_type.setStyleSheet("QComboBox{\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"    padding: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    image: url(:/gallery/arrow-down.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #E5383B;\n"
"    selection-background-color: #A4161A;\n"
"    color: #F5F3F4;\n"
"    background-color: #0B090A;\n"
"    border-radius: 5px;\n"
"}")
        self.output_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.output_type.setObjectName("output_type")
        self.output_type.addItem("")
        self.output_type.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 120, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.load_input = QtWidgets.QPushButton(self.centralwidget)
        self.load_input.setGeometry(QtCore.QRect(170, 330, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.load_input.sizePolicy().hasHeightForWidth())
        self.load_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.load_input.setFont(font)
        self.load_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_input.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BA181B;\n"
"}")
        self.load_input.setObjectName("load_input")
        self.load_preprocess = QtWidgets.QPushButton(self.centralwidget)
        self.load_preprocess.setGeometry(QtCore.QRect(130, 630, 200, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.load_preprocess.sizePolicy().hasHeightForWidth())
        self.load_preprocess.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        self.load_preprocess.setFont(font)
        self.load_preprocess.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_preprocess.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 20px;\n"
"    background-color: #0B090A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}")
        self.load_preprocess.setObjectName("load_preprocess")
        self.output_classes_label = QtWidgets.QLabel(self.centralwidget)
        self.output_classes_label.setGeometry(QtCore.QRect(270, 160, 120, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.output_classes_label.sizePolicy().hasHeightForWidth())
        self.output_classes_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.output_classes_label.setFont(font)
        self.output_classes_label.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.output_classes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_classes_label.setObjectName("output_classes_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 120, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.load_preprocess_error = QtWidgets.QLabel(self.centralwidget)
        self.load_preprocess_error.setGeometry(QtCore.QRect(35, 690, 380, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_preprocess_error.sizePolicy().hasHeightForWidth())
        self.load_preprocess_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.load_preprocess_error.setFont(font)
        self.load_preprocess_error.setStyleSheet("QLabel {\n"
"    color: #BA181B;\n"
"}")
        self.load_preprocess_error.setAlignment(QtCore.Qt.AlignCenter)
        self.load_preprocess_error.setObjectName("load_preprocess_error")
        self.predictions = QtWidgets.QLabel(self.centralwidget)
        self.predictions.setEnabled(True)
        self.predictions.setGeometry(QtCore.QRect(480, 400, 492, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.predictions.sizePolicy().hasHeightForWidth())
        self.predictions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.predictions.setFont(font)
        self.predictions.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.predictions.setText("")
        self.predictions.setTextFormat(QtCore.Qt.PlainText)
        self.predictions.setScaledContents(False)
        self.predictions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.predictions.setWordWrap(True)
        self.predictions.setObjectName("predictions")
        self.predictions_info = QtWidgets.QLabel(self.centralwidget)
        self.predictions_info.setGeometry(QtCore.QRect(645, 340, 160, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.predictions_info.sizePolicy().hasHeightForWidth())
        self.predictions_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.predictions_info.setFont(font)
        self.predictions_info.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.predictions_info.setTextFormat(QtCore.Qt.PlainText)
        self.predictions_info.setScaledContents(False)
        self.predictions_info.setAlignment(QtCore.Qt.AlignCenter)
        self.predictions_info.setWordWrap(True)
        self.predictions_info.setObjectName("predictions_info")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(450, 20, 1, 700))
        self.line.setStyleSheet("QFrame{\n"
"    background-color: #E5383B;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.load_model = QtWidgets.QPushButton(self.centralwidget)
        self.load_model.setGeometry(QtCore.QRect(625, 260, 200, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.load_model.sizePolicy().hasHeightForWidth())
        self.load_model.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.load_model.setFont(font)
        self.load_model.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_model.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 20px;\n"
"    background-color: #0B090A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}")
        self.load_model.setObjectName("load_model")
        self.model_info = QtWidgets.QLabel(self.centralwidget)
        self.model_info.setGeometry(QtCore.QRect(480, 37, 492, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.model_info.sizePolicy().hasHeightForWidth())
        self.model_info.setSizePolicy(sizePolicy)
        self.model_info.setMinimumSize(QtCore.QSize(480, 0))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        self.model_info.setFont(font)
        self.model_info.setStyleSheet("QLabel {\n"
"    color: #F5F3F4;\n"
"}")
        self.model_info.setTextFormat(QtCore.Qt.PlainText)
        self.model_info.setScaledContents(False)
        self.model_info.setAlignment(QtCore.Qt.AlignCenter)
        self.model_info.setWordWrap(True)
        self.model_info.setObjectName("model_info")
        self.load_classes = QtWidgets.QPushButton(self.centralwidget)
        self.load_classes.setGeometry(QtCore.QRect(360, 200, 41, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.load_classes.sizePolicy().hasHeightForWidth())
        self.load_classes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.load_classes.setFont(font)
        self.load_classes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_classes.setStyleSheet("QPushButton {\n"
"    color: #F5F3F4;\n"
"    border: 2px solid #E5383B;\n"
"    border-radius: 15px;\n"
"    background-color: #0B090A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A4161A;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BA181B;\n"
"}")
        self.load_classes.setObjectName("load_classes")
        NN2GUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NN2GUI)
        self.statusbar.setObjectName("statusbar")
        NN2GUI.setStatusBar(self.statusbar)

        self.retranslateUi(NN2GUI)
        QtCore.QMetaObject.connectSlotsByName(NN2GUI)

    def retranslateUi(self, NN2GUI):
        _translate = QtCore.QCoreApplication.translate
        NN2GUI.setWindowTitle(_translate("NN2GUI", "NN2GUI"))
        self.model_spec.setText(_translate("NN2GUI", "Model Size"))
        self.enter_input.setText(_translate("NN2GUI", "Enter Input"))
        self.framework_type.setItemText(0, _translate("NN2GUI", "TensorFlow"))
        self.framework_type.setItemText(1, _translate("NN2GUI", "PyTorch"))
        self.label_3.setText(_translate("NN2GUI", "Output Type"))
        self.label_5.setText(_translate("NN2GUI", "Input"))
        self.output_classes.setText(_translate("NN2GUI", "Change"))
        self.input_input.setPlaceholderText(_translate("NN2GUI", "Type Your Input Here ..."))
        self.input_type.setItemText(0, _translate("NN2GUI", "Image"))
        self.input_type.setItemText(1, _translate("NN2GUI", "Tabular"))
        self.input_type.setItemText(2, _translate("NN2GUI", "Text"))
        self.input_type.setItemText(3, _translate("NN2GUI", "Other"))
        self.output_type.setItemText(0, _translate("NN2GUI", "Classification"))
        self.output_type.setItemText(1, _translate("NN2GUI", "Regression"))
        self.label.setText(_translate("NN2GUI", "Input Type"))
        self.load_input.setText(_translate("NN2GUI", "Load File"))
        self.load_preprocess.setText(_translate("NN2GUI", "Load Preprocess"))
        self.output_classes_label.setText(_translate("NN2GUI", "Output Classes"))
        self.label_2.setText(_translate("NN2GUI", "Framework"))
        self.load_preprocess_error.setText(_translate("NN2GUI", "Error"))
        self.predictions_info.setText(_translate("NN2GUI", "Predictions"))
        self.load_model.setText(_translate("NN2GUI", "Load Model"))
        self.model_info.setText(_translate("NN2GUI", "Waiting passionately for a model!"))
        self.load_classes.setText(_translate("NN2GUI", " ▲"))
